# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtTjHlnq98h2XJUxvxzMkdY5QMaDj49y
"""

# Cria uma lista vazia global para armazenar os dados de todos os alunos cadastrados
banco_dados_alunos = []

# Define a função responsável por coletar os nomes e as notas
def cadastrar_aluno():
    # Inicia um laço de repetição infinito para permitir múltiplos cadastros
    while True:
        # Solicita o nome, remove espaços extras e armazena na variável
        nome = input("\nDigite o nome do Aluno: ").strip()

        # Tenta executar o bloco de código abaixo (captura de notas)
        try:
            # Converte a entrada do usuário para número decimal (float)
            n1 = float(input(f"Digite a 1ª nota de {nome}: "))
            if n1  < 0 or n1 > 10.0:
                print("Erro: A nota deve estar entre 0 e 10!")
                continue
            # Converte a segunda nota para decimal
            n2 = float(input(f"Digite a 2ª nota de {nome}: "))
        # Caso o usuário digite algo que não seja número, o sistema não trava
        except ValueError:
            # Exibe mensagem de erro amigável
            print("Erro: Digite apenas números para as notas!")
            # Volta para o início do loop 'while' (pede o nome novamente)
            continue

        # Calcula a média aritmética das duas notas
        media = (n1 + n2) / 2

        # Estrutura condicional para definir a situação do aluno
        if media >= 7.0:
            situacao = "APROVADO"
        # Verifica se está na faixa de recuperação (entre 5.0 e 6.9)
        elif media >= 5.0:
            situacao = "RECUPERACAO"
        # Se for menor que 5.0, entra no senão
        else:
            situacao = "REPROVADO"

        # Organiza os dados do aluno atual em um formato de Dicionário (chave: valor)
        aluno = {
            "nome": nome,
            "media": media,
            "situacao": situacao
        }
        # Adiciona o dicionário do aluno à nossa lista global (banco de dados)
        banco_dados_alunos.append(aluno)

        # Exibe o resultado imediato do cálculo para o usuário
        print(f"Média: {media:.1f} - Situação: {situacao}")

        # Pergunta se o usuário quer continuar no loop de cadastro
        cont = input("\nDeseja cadastrar outro aluno? [1]-Sim | [Outra tecla]-Voltar: ")
        # Se a resposta for diferente de "1", encerra o laço 'while'
        if cont != "1":
            # Sai da função e volta para onde ela foi chamada (o menu)
            break

# Define a função que processa e exibe as estatísticas da turma
def exibir_relatorio():
    # Verifica se a lista de alunos está vazia
    if not banco_dados_alunos:
        # Se estiver vazia, avisa o usuário e interrompe a função com 'return'
        print("\n[!] Nenhum aluno cadastrado no sistema.")
        return

    # Estética visual para o topo do relatório
    print("\n" + "="*30)
    print("      RELATÓRIO DA TURMA")
    print("="*30)

    # Conta quantos itens existem na lista banco_dados_alunos
    total = len(banco_dados_alunos)
    # Usa compreensão de lista para contar quantos alunos têm situação "APROVADO"
    aprovados = sum(1 for a in banco_dados_alunos if a['situacao'] == "APROVADO")
    # Faz o mesmo para contar quem está em "RECUPERACAO"
    recuperacao = sum(1 for a in banco_dados_alunos if a['situacao'] == "RECUPERACAO")
    # Faz o mesmo para contar os "REPROVADOS"
    reprovados = sum(1 for a in banco_dados_alunos if a['situacao'] == "REPROVADO")
    # Soma todas as médias individuais para calcular a média geral depois
    soma_medias = sum(a['media'] for a in banco_dados_alunos)

    # Percorre cada aluno na lista para listar os nomes e médias um por um
    for a in banco_dados_alunos:
        # Exibe os dados formatados com uma casa decimal (:.1f)
        print(f"Aluno: {a['nome']} | Média: {a['media']:.1f} | Status: {a['situacao']}")

    # Exibe o resumo estatístico final
    print("-" * 30)
    print(f"Total de alunos: {total}")
    print(f"Aprovados: {aprovados} | Recuperação: {recuperacao} | Reprovados: {reprovados}")
    # Calcula a média da turma dividindo a soma total pelo número de alunos
    print(f"Média Geral: {(soma_medias/total):.1f}")
    print("=" * 30)

# Define a função que controla a navegação principal do programa
def menu_principal():
    # Mantém o menu ativo até que o usuário escolha sair
    while True:
        # Interface do menu principal
        print("\n|=======[Sistema Escolar]=======|")
        print("[1]-Cadastrar Alunos e Notas")
        print("[2]-Exibir Relatório Final")
        print("[3]-Sair")

        # Recebe a opção do teclado
        opcao = input("Selecione a Opção: ")

        # Se escolher 1, chama a função de cadastro
        if opcao == "1":
            cadastrar_aluno()
        # Se escolher 2, chama a função de relatório
        elif opcao == "2":
            exibir_relatorio()
        # Se escolher 3, entra na rotina de saída
        elif opcao == "3":
            # Pede uma confirmação extra e transforma em maiúsculo (.upper)
            confirmar = input("Deseja realmente sair? [S/N]: ").upper()
            # Se confirmar com 'S', quebra o loop do menu
            if confirmar == "S":
                print("Encerrando sistema... Logout efetuado.")
                break
        # Tratamento para caso o usuário digite um número que não está no menu
        else:
            print("Opção inválida!")

# Verifica se este script está sendo executado diretamente (boa prática em Python)
if __name__ == "__main__":
    # Inicia o programa chamando a primeira função
    menu_principal()